version: "3"

services:
    nginx:
        restart: always
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./config/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
       # networks:
        #    backfires:
        #        ipv4_address: 127.0.0.1:8080
       # extra_hosts:
        #    - "jsonplaceholder.typicode.com:104.21.55.162"
        #ports:
           # - "127.0.0.1:8080:8080"
       # network_mode: host

